### ISSUE TITLE
Relations removed by subsequent flush

### ISSUE THREAD

**Issue by liutec** [lphuberdeau/Neo4j-PHP-OGM#102]
The last asserts will fail in the following test case if a reverse relation is added to the book entity:
```
    /**
     * @OGM\ManyToMany(relation="BasedOn", direction="from")
     */
    protected $sagas;
```

```
    function testRelationIntegrityOnMultipleFlush()
    {
        $em = $this->getEntityManager();

        $book = new Entity\Book();
        $saga = new Entity\Saga();
        $saga->setTitle('A tale of two cities');
        $book->setName('A tale of two cities');
        $book->addSaga($saga);
        $saga->setBook($book);
        $em->persist($book);
        $em->persist($saga);
        $em->flush();

        $query = $em->createCypherQuery()
            ->startWithNode("book", array($book))
            ->match("(saga)<-[:BasedOn]-book")
            ->end("saga");

        $testSaga = $query->getOne();
        $this->assertEquals($testSaga->getId(), $saga->getId());

        $em->persist($saga);
        $em->flush();

        $testSaga = $query->getOne();
        $this->assertNotNull($testSaga); // fails
        $this->assertEquals($testSaga->getId(), $saga->getId());
    }
```

**Comment by lphuberdeau** [comment]
This seems like it may be related to the query not being re-executed and
the iterator having reached the end.

If this is the case, it would be a normal behavior.

**Comment by liutec** [comment]
The query is executed properly on both calls. 
The problem is that the relation is not re-created if deleted by removePreviousRelations because addRelation does the proper direction check and finds the relation cached in getRelationsFrom.
The test passes with the direction check implemented in removePreviousRelations .

**Comment by liutec** [comment]
Were you able to confirm this as an issue?

**Comment by lphuberdeau** [comment]
Could you make sure the test re-issues the query to confirm the issue?

**Comment by liutec** [comment]
Sorry, it took me a while to understand. The query is issued both times during the test (just checked). Also, if the query was not issued the second time, the test would have passed.

**Comment by liutec** [comment]
The issue is that relations are deleted from Neo4j by the second flush.
