### ISSUE TITLE
Update Entity Property

### ISSUE THREAD

**Issue by dan89** [lphuberdeau/Neo4j-PHP-OGM#91]
Hi,
I can't seem to update a Property on an entity.
I have defined a setter like this:

/**
     * @OGM\Property
     * @OGM\Index
     * @var string
     */
protected $field;

public function setField($field) {
     $this->field = $field;
     return $this;
}

on $o->setField('x');
$em->persist($o);
$em->flush();

Nothing happens. Am I doing something wrong ?

**Comment by lphuberdeau** [comment]
Seems like it should work. Perhaps a more complete sample would help?

**Comment by dan89** [comment]
What I was trying to say is that the node's property isn't updated after flush in the Neo4j database.

**Comment by lphuberdeau** [comment]
I don't have enough to work with to help. There are quite a few tests making sure the basic functionality works. Please post enough code to reproduce the issue.

Even better if you can write a failing test that demonstrates the issue.

**Comment by dan89** [comment]
Louis, I don't see anywhere in the tests or
